name: NewYearUpdateCopyright.yml – New Year LICENSE Reminder

on:
  schedule:
    - cron: '0 5 1 1 *'  # Midnight EST on Jan 1 America/New_York
  #workflow_dispatch:

permissions:
  issues: write
  contents: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Create LICENSE update issue
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4.0.1
        with:
          title: "Update LICENSE for the new year"
          content-filepath: .github/license-reminder.md
          assignees: RalphHightower
          labels: |
            maintenance
            license