name: NewYearUpdateCopyright.yml – New Year LICENSE Reminder

on:
  schedule:
    - cron: '0 5 1 1 *'  # Midnight EST on Jan 1 America/New_York
  #workflow_dispatch:

permissions: none

jobs:
  permissions:
    issues: write
    contents: read
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create LICENSE update issue
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6.0.0
        with:
          title: "Update LICENSE for the new year"
          content-filepath: .github/license-reminder.md
          assignees: RalphHightower
          labels: |
            maintenance
            license
