name: New Year LICENSE Reminder

on:
  schedule:
    - cron: '0 5 1 1 *'  # Midnight EST on Jan 1 America/New_York
  #workflow_dispatch:

permissions: {}

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create LICENSE update issue
        permissions:
          issues: write
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Update LICENSE for the new year"
          content-filepath: .github/license-reminder.md
          labels: |
            maintenance
            license