name: release-please.yml – Automate releases with Conventional Commit Messages.
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2.10.3
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - uses: step-security/harden-runner@v2.10.3 # v4.1.3
      with:
        contents: write
        pull-requests: write
        # this assumes that you have created a personal access token
        # (PAT) and configured it as a GitHub action secret named
        # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
        token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
        release-type: simple
